In [83]:
import pandas as pd
import regex as re

In [84]:
df1 = pd.read_parquet("../data/raw/receivings.parquet")
df2 = pd.read_csv("../data/raw/commodity_survey.csv")

C:\Users\cjchen\AppData\Local\Temp\1\ipykernel_33248\2829705772.py:2: DtypeWarning: Columns (2,6,19,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv("../data/raw/commodity_survey.csv")

In [85]:
df2

,Commodity,Time Frame,Survey ID,Survey ID Status,UIN,Selling Country/Region,Vendor Number,Vendor Name,UIN of Origin,Vendor Common Name,...,V_Alternative_Fiber_Type,V_Ancient_and_Endangered_Forest,V_Bleaching_Process,V_Eucalyptus_Amount,V_Largest_Grain_Trader,V_Estimated_Acres,V_NAMP_Code,V_Establishment_Code,V_Trim_Spec,V_Marbling_Grade
0,Beef,FY24,Null,Complete,USA-36355-Null,USA,36355,Sandridge Food Corp,USA-36355,Sandridge Food Corp,...,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null
1,Beef,FY24,Null,Complete,USA-30153-Null,USA,30153,IBP/Tyson,USA-30153,IBP/Tyson,...,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null
2,Beef,FY24,Null,Complete,USA-32038-Null,USA,32038,NATIONAL,USA-32038,NATIONAL,...,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null
3,Beef,FY24,Null,Complete,USA-47919-Null,USA,47919,ONE WORLD,USA-47919,ONE WORLD,...,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null
4,Beef,FY24,Null,Complete,USA-33238-Null,USA,33238,HARRIS RANCH,USA-33238,HARRIS RANCH,...,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43605,Coffee,FY25,Null,Not Started,JPN-2050-45576,JPN,2050.0,"Hamaya Co., Ltd.",Null,Hamaya Co,...,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null
43606,Coffee,FY25,Null,Not Started,JPN-4669-25364,JPN,4669.0,UNITED FOODS INTL.,Null,United Foods Intl,...,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null
43607,Coffee,FY25,Null,Not Started,USA-30935-1114676,USA,30935.0,NESTLE USA INC,Null,Nestle,...,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null
43608,Coffee,FY25,Null,Not Started,USA-30935-1872928,USA,30935.0,NESTLE USA INC,Null,Nestle,...,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null
43609,Coffee,FY25,Null,Not Started,USA-30935-1927685,USA,30935.0,NESTLE USA INC,Null,Nestle,...,Null,Null,Null,Null,Null,Null,Null,Null,Null,Null

In [86]:
df3 = pd.read_csv("../data/raw/volume_map.csv")

In [87]:
df3[df3["Parent Activity EF Label"].str.contains("Beef|Pork|Chicken", case=False, na=False)]

,REGION,ITEM_NUM,DEPARTMENT_NUM,MAJOR_CATEGORY_DESC,GROUP_CATEGORY_DESC,ITEM_CATEGORY_DESC,ITEM_DESC_1,ITEM_DESC_2,Receiving USD,Receiving Units,Receiving KGs,Detailed Activity EF Label,Parent Activity EF Label,Volume EF Reference Number
3,USA,52245.0,61,MEAT DEPARTMENT ORDER GUIDE,MEAT DEPARTMENT ORDER NUMBERS,BEEF,BEEF RIBEYE WHOLE,BONELESS USDA CHOICE,"$511,780,238","42,158,055","19,122,557","Beef, fresh meat, at slaughterhouse /US U",Beef,14
4,USA,72451.0,61,MEAT DEPARTMENT ORDER GUIDE,MEAT DEPARTMENT ORDER NUMBERS,BEEF,BEEF LOIN TOP LOIN WHOLE,(NEW YORK) USDA CHOICE,"$498,696,201","56,182,084","25,483,744","Beef, fresh meat, at slaughterhouse /US U",Beef,14
6,USA,1025795.0,17,EGGS,CAGE FREE EGGS,CAGE FREE LARGE MEDIUM,KS CAGE FREE AA LARGE 5DZ,SL21 P120 / P132 / P144,"$425,958,805","32,905,317",NaN,"Chicken egg, poultry industrial laying systems...",Chicken egg,31
9,USA,29543.0,61,MEAT DEPARTMENT ORDER GUIDE,MEAT DEPARTMENT ORDER NUMBERS,BEEF,CHUCK ROLLS 1X1,NaN,"$331,585,622","74,103,658","33,612,827","Beef, fresh meat, at slaughterhouse /US U",Beef,14
11,CAN,55503.0,61,MEAT,POULTRY,KS CHICKEN,KS CHICKEN BREASTS,BONELESS SKINLESS,"$304,038,204","31,075,258","31,075,258","Chicken, fresh meat, at slaughterhouse /US U",Chicken,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11453,CAN,91876.0,61,SEASONED PRODUCTS,PORK,PORK,EXTRA LEAN GROUND PORK,ORGANIC / 3X700G /2.1KG,NaN,NaN,NaN,"Pork, fresh meat, at slaughterhouse /US U",Pork,84
11485,USA,923478.0,17,EGGS,CONVENTIONAL EGGS,CONVENTIONAL LARGE MEDIUM,MEDIUM AA LOOSE EGGS 15DZ,DOM 30/SL 21,NaN,NaN,NaN,"Chicken egg, poultry industrial laying systems...",Chicken egg,31
11538,USA,949952.0,17,EGGS,CONVENTIONAL EGGS,CONVENTIONAL LARGE MEDIUM,USDA LARGE EGGS 5DZ,BBS,NaN,NaN,NaN,"Chicken egg, poultry industrial laying systems...",Chicken egg,31
11544,USA,960031.0,17,EGGS,OTHER EGGS,LIQUID EGGS,WHOLE LIQUID EGG 40 LBS,DOM 40/SL 24 T6H10P60,NaN,NaN,NaN,"Chicken egg, poultry industrial laying systems...",Chicken egg,31
11565,USA,986046.0,17,EGGS,ORGANIC EGGS,ORGANIC LARGE MEDIUM,ORGANIC MEDIUM EGGS,5 DOZEN,NaN,NaN,NaN,"Chicken egg, poultry industrial laying systems...",Chicken egg,31

In [88]:
df2['Department'].unique()

array(['D63 - Service Deli', 'D88 - Food Court', 'D68 - Raw Materials',
       'D61 - Meat', 'D12 - Candy', 'D19 - Deli', 'D14 - Sundries',
       'D17 - Cooler', 'D18 - Frozen Foods', 'D13 - Food', 'D62 - Bakery',
       'D20 - Health & Beauty', 'See Raw Data', 'D33 - Small Appliances',
       'D24 - Major Appliances/Electronics', 'D27 - Lawn & Garden',
       'D93 - Pharmacy OTC', 'DN/A - Receipts/Promotional Material',
       'D28 - Toys / Seasonal', 'D21 - Office Supplies', 'D64 - Seafood',
       'D44 - Roadshow', 'D92 - Pharmacy'], dtype=object)

In [89]:
df1_unique = df1.groupby('UIN').agg({
    'region': "first",
    "dpmt_num": "first",
    'cat1_desc': "first",
    'cat12_desc': "first",
    'cat123_desc': "first",
    "item_desc_1": "first",
    "item_desc_2": "first"
}).reset_index()

df1_unique['cat1_desc'] = df1_unique['cat1_desc'].apply(lambda x: x.split('-', 1)[1].strip() if pd.notnull(x) and '-' in x else x)
df1_unique['cat12_desc'] = df1_unique['cat12_desc'].apply(lambda x: x.split('-', 1)[1].strip() if pd.notnull(x) and '-' in x else x)
df1_unique['cat123_desc'] = df1_unique['cat123_desc'].apply(lambda x: x.split('-', 1)[1].strip() if pd.notnull(x) and '-' in x else x)

In [90]:
df2_clean = df2[['UIN', 'Selling Country/Region', 'Department', 'Category 1 Description', 'Category 2 Description', 'Category 3 Description', 'Item Desc. 1', 'Item Desc. 2', 'Commodity']].copy()
df2_clean.columns = ['uin', 'region', 'dpmt_num', 'cat1_desc', 'cat12_desc', 'cat123_desc', 'item_desc_1', 'item_desc_2', 'commodity']
df2_clean

,uin,region,dpmt_num,cat1_desc,cat12_desc,cat123_desc,item_desc_1,item_desc_2,commodity
0,USA-36355-Null,USA,D63 - Service Deli,Null,Null,Null,Null,Null,Beef
1,USA-30153-Null,USA,D88 - Food Court,Null,Null,Null,Null,Null,Beef
2,USA-32038-Null,USA,D68 - Raw Materials,Null,Null,Null,Null,Null,Beef
3,USA-47919-Null,USA,D88 - Food Court,Null,Null,Null,Null,Null,Beef
4,USA-33238-Null,USA,D88 - Food Court,Null,Null,Null,Null,Null,Beef
...,...,...,...,...,...,...,...,...,...
43605,JPN-2050-45576,JPN,D88 - Food Court,C INGREDINET,CB DOMESTIC,CAA INGREDIENT,ESPRESSO WHOLE BEAN,1KG*6/CS,Coffee
43606,JPN-4669-25364,JPN,D88 - Food Court,C INGREDINET,CB DOMESTIC,CAA INGREDIENT,COLD BREW COFFEE 1L*12,COLD BREW COFFEE 1L*12,Coffee
43607,USA-30935-1114676,USA,D68 - Raw Materials,C-NON FOODS ITEMS,CN-NON FOODS ITEMS,CNF-NON FOODS ITEMS,STARBUCKS VIA INST 13CT,80/CS COLOMBIAN MED COFFE,Coffee
43608,USA-30935-1872928,USA,D68 - Raw Materials,S-SEASONAL CWI,SC-MISC SC,SCB-COFFEE BRICKS PACK,NESCAFE CAFE DE OLLA,Null,Coffee
43609,USA-30935-1927685,USA,D68 - Raw Materials,A-PATTIES,AA-PATTIES,AAB-PATTIES,NESCAFE GOLD BLONDE,ESPRESSO JAR,Coffee

In [91]:
def combine_features(row):
    # Use empty strings for NaNs
    r = str(row['region']).strip() if pd.notnull(row['region']) else ""
    d = re.search(r'\d+', str(row['dpmt_num'])).group() if re.search(r'\d+', str(row['dpmt_num'])) else "0"
    c1 = str(row['cat1_desc']).strip() if pd.notnull(row['cat1_desc']) else ""
    c2 = str(row['cat12_desc']).strip() if pd.notnull(row['cat12_desc']) else ""
    c3 = str(row['cat123_desc']).strip() if pd.notnull(row['cat123_desc']) else ""
    desc1 = str(row['item_desc_1']).strip()
    desc2 = str(row['item_desc_2']).strip()
    
    # We only include the label if the value exists, or keep it empty
    return f"Region: {r} | Department: {d} | Category: {c1} > {c2} > {c3} | Description: {desc1} {desc2}"

In [92]:
df3_clean = df3[(df3["Parent Activity EF Label"] == "Beef") | (df3["Parent Activity EF Label"] == "Pork") | (df3["Parent Activity EF Label"] == "Chicken")].copy()
df3_clean['commodity'] = df3_clean['Parent Activity EF Label'].apply(lambda x: "Beef" if re.search(r'Beef', x, re.IGNORECASE) else ("Pork" if re.search(r'Pork', x, re.IGNORECASE) else ("Chicken" if re.search(r'Chicken', x, re.IGNORECASE) else "Other")))

In [93]:
df3_clean = df3_clean[['REGION', 'ITEM_NUM', 'DEPARTMENT_NUM', 'MAJOR_CATEGORY_DESC', 'GROUP_CATEGORY_DESC', 'ITEM_CATEGORY_DESC', 'ITEM_DESC_1', 'ITEM_DESC_2', 'commodity']]
df3_clean.columns = ['region', 'item_num', 'dpmt_num', 'cat1_desc', 'cat12_desc', 'cat123_desc', 'item_desc_1', 'item_desc_2', 'commodity']

In [94]:
df2_clean = df2_clean.replace("Null", pd.NA)
df2_clean = df2_clean.dropna(subset=['cat1_desc', 'item_desc_1'])

In [95]:
df2_clean['commodity'].unique()

array(['Cocoa', 'Coffee', 'Energy STAR', 'Fiber', 'Palm Oil', 'Seafood',
       'Soy'], dtype=object)

In [96]:
df3_clean

,region,item_num,dpmt_num,cat1_desc,cat12_desc,cat123_desc,item_desc_1,item_desc_2,commodity
3,USA,52245.0,61,MEAT DEPARTMENT ORDER GUIDE,MEAT DEPARTMENT ORDER NUMBERS,BEEF,BEEF RIBEYE WHOLE,BONELESS USDA CHOICE,Beef
4,USA,72451.0,61,MEAT DEPARTMENT ORDER GUIDE,MEAT DEPARTMENT ORDER NUMBERS,BEEF,BEEF LOIN TOP LOIN WHOLE,(NEW YORK) USDA CHOICE,Beef
9,USA,29543.0,61,MEAT DEPARTMENT ORDER GUIDE,MEAT DEPARTMENT ORDER NUMBERS,BEEF,CHUCK ROLLS 1X1,NaN,Beef
11,CAN,55503.0,61,MEAT,POULTRY,KS CHICKEN,KS CHICKEN BREASTS,BONELESS SKINLESS,Chicken
12,USA,33841.0,61,MEAT,POULTRY,CONVENTIONAL CHICKEN,FRESH FRYER BREAST,BONELESS SKINLESS,Chicken
...,...,...,...,...,...,...,...,...,...
11439,USA,91636.0,61,MEAT DEPARTMENT ORDER GUIDE,MEAT DEPARTMENT ORDER NUMBERS,BEEF,BEEF OX TAIL,NaN,Beef
11440,CAN,91658.0,61,PERISHABLES,MEAT,BEEF ROE 61,BONE-IN SHORT RIB,"""HAMMER STYLE""",Beef
11451,CAN,91873.0,61,MEAT,BEEF,ORGANIC BEEF ABF,KS LEAN GROUND BEEF,ORGANIC,Beef
11452,CAN,91874.0,61,SEASONED PRODUCTS,BEEF,ORGANIC BEEF ABF,GROUND BISON EXTRA LEAN,2 X 454 G / 908 G,Beef
11453,CAN,91876.0,61,SEASONED PRODUCTS,PORK,PORK,EXTRA LEAN GROUND PORK,ORGANIC / 3X700G /2.1KG,Pork

In [97]:
df4 = pd.read_csv("../data/raw/fy24_ksprotein.csv")

In [98]:
df4_clean = df4[['UIN', 'REGION', 'DEPT.', 'ITEM NUM.',
        'CAT. 1 - DESC.', 'CAT. 12 - DESC.', 'CAT. 123 - DESC.', 
        'ITEM DESC. 1', 'ITEM DESC. 2', 'PRIMARY LABEL']].copy()
df4_clean.columns = ['uin', 'region', 'dpmt_num', 'item_num', 'cat1_desc', 'cat12_desc', 'cat123_desc', 'item_desc_1', 'item_desc_2', 'commodity']
df4_clean

,uin,region,dpmt_num,item_num,cat1_desc,cat12_desc,cat123_desc,item_desc_1,item_desc_2,commodity
0,US-29361-6406,US,12,6406,G-MEAT SNACKS,GZ-MEAT SNACKS,GZB-MEAT SNACKS BEEF,KS STEAK STRIPS 12OZ 340G,C30T5H3 P450 SL300,BEEF
1,US-29361-6406,US,12,6406,G-MEAT SNACKS,GZ-MEAT SNACKS,GZB-MEAT SNACKS BEEF,KS STEAK STRIPS 12OZ 340G,C30T5H3 P450 SL300,BEEF
2,US-29361-6406,US,12,6406,G-MEAT SNACKS,GZ-MEAT SNACKS,GZB-MEAT SNACKS BEEF,KS STEAK STRIPS 12OZ 340G,C30T5H3 P450 SL300,BEEF
3,US-29361-1259073,US,12,1259073,G-MEAT SNACKS,GZ-MEAT SNACKS,GZT-MEAT SNACKS TURKEY,KS TURKEY JERKY 13.5OZ,383G P450 C30 5T3H,POULTRY
4,US-29361-1259073,US,12,1259073,G-MEAT SNACKS,GZ-MEAT SNACKS,GZT-MEAT SNACKS TURKEY,KS TURKEY JERKY 13.5OZ,383G P450 C30 5T3H,POULTRY
...,...,...,...,...,...,...,...,...,...,...
2250,US-65231-1380549,US,88,1380549,A-RAW INGREDIENTS,AA-MEATS,AAA-MEAT,KS FROZEN FRANKS ALL BEEF,PRICESMART,BEEF
2251,US-33057-580496,US,88,580496,A-RAW INGREDIENTS,AA-MEATS,AAA-MEAT,KS PORK DINNER FRANKS,FOR TAIWAN ONLY T15H4P60,PORK
2252,US-36083-1851758,US,88,1851758,A-RAW INGREDIENTS,AA-MEATS,AAN-INGREDIENT,BACON CHUTNEY 6/3LB TUBS,T10H6P60 DOM60,PORK
2253,US-36083-1851758,US,88,1851758,A-RAW INGREDIENTS,AA-MEATS,AAN-INGREDIENT,BACON CHUTNEY 6/3LB TUBS,T10H6P60 DOM60,PORK
2254,US-30077-1463058,US,88,1463058,A-RAW INGREDIENTS,AA-MEATS,AAA-MEAT,FROZEN CHICKEN BAKE 40CT,75DOM T8H7P56,"POULTRY, PORK, DAIRY"

In [99]:
combined_df = pd.concat([df2_clean, df3_clean, df4_clean], ignore_index=True, join='inner')

In [100]:
combined_df

,region,dpmt_num,cat1_desc,cat12_desc,cat123_desc,item_desc_1,item_desc_2,commodity
0,JPN,D62 - Bakery,B-NOT FOR SALES,BK-FROZEN AND COLD STORAGE,BAA-FROZEN STORAGE ITEM,COCOA ORANGE COUNTRY LOAF,280G 16EA/CT 70CS/PL,Cocoa
1,CAN,D12 - Candy,G-MULTI SERVE CANDY,GA-FRUIT SNACKS,GAB-FRUITY SNACKS,KS DKCHOC CVD MANGO 20.4Z,T96H4 P384 SL260,Cocoa
2,GBR,D12 - Candy,N-FRUIT SNACKS,NA-FRUIT SNACKS,NAA-FRUIT SNACKS,KS DARK CHOC MANGO 580G,L96/P384,Cocoa
3,USA,D12 - Candy,F-BULK GOOD CANDY,FA-WRAPPED AND UNWRAPPED,FAK-BULK KIRKLAND,KS DKCHOC CVD MANGO 20.4Z,T96H4 P384 SL260,Cocoa
4,CAN,D62 - Bakery,H-HOLD,HL-HOLD,HLD-HOLD,GOLD TRIANGLE CHOCOLATE,<NA>,Cocoa
...,...,...,...,...,...,...,...,...
23579,US,88,A-RAW INGREDIENTS,AA-MEATS,AAA-MEAT,KS FROZEN FRANKS ALL BEEF,PRICESMART,BEEF
23580,US,88,A-RAW INGREDIENTS,AA-MEATS,AAA-MEAT,KS PORK DINNER FRANKS,FOR TAIWAN ONLY T15H4P60,PORK
23581,US,88,A-RAW INGREDIENTS,AA-MEATS,AAN-INGREDIENT,BACON CHUTNEY 6/3LB TUBS,T10H6P60 DOM60,PORK
23582,US,88,A-RAW INGREDIENTS,AA-MEATS,AAN-INGREDIENT,BACON CHUTNEY 6/3LB TUBS,T10H6P60 DOM60,PORK
23583,US,88,A-RAW INGREDIENTS,AA-MEATS,AAA-MEAT,FROZEN CHICKEN BAKE 40CT,75DOM T8H7P56,"POULTRY, PORK, DAIRY"

In [101]:
combined_df['dpmt_num'] = combined_df['dpmt_num'].apply(lambda x: re.search(r'\d+', str(x)).group() if re.search(r'\d+', str(x)) else "0")
combined_df['commodity'] = combined_df['commodity'].str.strip().str.upper()

In [102]:
combined_df['cat123_desc'].str.contains('-').sum() / len(combined_df)

0.8793249660786974

In [103]:
combined_df = combined_df.dropna(subset=['cat1_desc', 'cat12_desc', 'item_desc_1']).copy()
def clean_category_split(cat_string):
    # Handle NaN or null values safely
    if not isinstance(cat_string, str):
        return ""
        
    # Split on the first hyphen, grab the last resulting item, and strip whitespace
    return cat_string.split('-', 1)[-1].strip()
for col in ['cat1_desc', 'cat12_desc', 'cat123_desc']:
    combined_df[col] = combined_df[col].apply(clean_category_split)

combined_df['concatenated_text'] = combined_df.apply(combine_features, axis=1)
combined_df['commodity'] = combined_df['commodity'].str.replace('CHICKEN', 'POULTRY')

In [104]:
combined_df.to_csv("../data/processed/combined_commodity_data.csv", index=False)

In [105]:
combined_df

,region,dpmt_num,cat1_desc,cat12_desc,cat123_desc,item_desc_1,item_desc_2,commodity,concatenated_text
0,JPN,62,NOT FOR SALES,FROZEN AND COLD STORAGE,FROZEN STORAGE ITEM,COCOA ORANGE COUNTRY LOAF,280G 16EA/CT 70CS/PL,COCOA,Region: JPN | Department: 62 | Category: NOT F...
1,CAN,12,MULTI SERVE CANDY,FRUIT SNACKS,FRUITY SNACKS,KS DKCHOC CVD MANGO 20.4Z,T96H4 P384 SL260,COCOA,Region: CAN | Department: 12 | Category: MULTI...
2,GBR,12,FRUIT SNACKS,FRUIT SNACKS,FRUIT SNACKS,KS DARK CHOC MANGO 580G,L96/P384,COCOA,Region: GBR | Department: 12 | Category: FRUIT...
3,USA,12,BULK GOOD CANDY,WRAPPED AND UNWRAPPED,BULK KIRKLAND,KS DKCHOC CVD MANGO 20.4Z,T96H4 P384 SL260,COCOA,Region: USA | Department: 12 | Category: BULK ...
4,CAN,62,HOLD,HOLD,HOLD,GOLD TRIANGLE CHOCOLATE,<NA>,COCOA,Region: CAN | Department: 62 | Category: HOLD ...
...,...,...,...,...,...,...,...,...,...
23579,US,88,RAW INGREDIENTS,MEATS,MEAT,KS FROZEN FRANKS ALL BEEF,PRICESMART,BEEF,Region: US | Department: 88 | Category: RAW IN...
23580,US,88,RAW INGREDIENTS,MEATS,MEAT,KS PORK DINNER FRANKS,FOR TAIWAN ONLY T15H4P60,PORK,Region: US | Department: 88 | Category: RAW IN...
23581,US,88,RAW INGREDIENTS,MEATS,INGREDIENT,BACON CHUTNEY 6/3LB TUBS,T10H6P60 DOM60,PORK,Region: US | Department: 88 | Category: RAW IN...
23582,US,88,RAW INGREDIENTS,MEATS,INGREDIENT,BACON CHUTNEY 6/3LB TUBS,T10H6P60 DOM60,PORK,Region: US | Department: 88 | Category: RAW IN...
23583,US,88,RAW INGREDIENTS,MEATS,MEAT,FROZEN CHICKEN BAKE 40CT,75DOM T8H7P56,"POULTRY, PORK, DAIRY",Region: US | Department: 88 | Category: RAW IN...